### ISSUE TITLE
How can i use it with gin ?

### ISSUE THREAD

**Issue by LeaderBoy** [jpillora/go-upgrade#63]
I can't find any documentation about using gin and overseer together.Below is my code, how can I use them together?
```
router := gin.Default()
router.Use(tlsHandler())
router.RunTLS(":8080", ".pem", ".key")
```

**Comment by jpillora** [comment]
Untested, though something like:

```go
router := gin.Default()
router.Use(tlsHandler())
l := state.Listener()
l = tls.NewListener(l, &tls.Config{
  //use your cert/key
})
router.RunListener(l)
```


https://pkg.go.dev/github.com/gin-gonic/gin#Engine.RunListener

**Comment by LeaderBoy** [comment]
@jpillora  Thank you so much for your quick reply, I tested your code.
The following is the correct version


> Untested, though something like:
> 
> ```go
> router := gin.Default()
> router.Use(tlsHandler())
> l := state.Listener
> l = tls.NewListener(l, &tls.Config{
>   //use your cert/key
> })
> router.RunListener(l)
> ```
> 
> https://pkg.go.dev/github.com/gin-gonic/gin#Engine.RunListener

I would be even more grateful if there is a complete tutorial using the supervisor

**Comment by jpillora** [comment]
What’s the supervisor?

**Comment by LeaderBoy** [comment]
@jpillora  you say "Works with process managers (systemd, upstart, supervisor, etc)"
[supervisord.org](http://supervisord.org/)

**Comment by jpillora** [comment]
Ah it works like any other process managed by supervisor. Overseer allows
your process to do an upgrade-restart, which supervisor doesn’t detect
