### ISSUE TITLE
restart server : accept tcp 127.0.0.1:9507: use of closed network connection

### ISSUE THREAD

**Issue by dxxjing** [jpillora/go-upgrade#78]
Simulate a time-consuming request, restart during the request process, and find that the old process cannot wait for the request to complete before exiting

**Comment by dxxjing** [comment]
Reason found

**Comment by bourne-3** [comment]
> Reason found
I'm experiencing the same problem with the following error
```
accept tcp [::]:5001: use of closed network connection
```
I'm using the framework gin and this error occurs in restart.

**Comment by jpillora** [comment]
I think you can change the restart signal

**Comment by glaslos** [comment]
@dxxjing what was the solution?
@bourne-3 did you solve this in combination with gin?

**Comment by glaslos** [comment]
Solved by implementing graceful restart with Chi: https://github.com/go-chi/chi/blob/master/_examples/graceful/main.go
